title: Red Bull Abu Dhabi 2022 - analysis
author: Jesse Sallis
# logo: logo.png
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js